version: '3.1'

volumes:
  vol_mongo:

services:
  mongo:
    image: mongo
    restart: always
    volumes:
     - vol_mongo:/data/db1
    environment:
      MONGO_INITDB_ROOT_USER: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopasswd

  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopasswd
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopasswd@mongo:27017/