version: '3.1'

volumes:
  vol_maria:

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    volumes:
     - vol_maria:/data/db2
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
