version: '3.1'

services:
  redis:
    image: redis:7.0.8
    restart: always

  commander:
    image: rediscommander/redis-commander
    restart: always
    ports:
     - 8081:8081
    environment:
      REDIS_HOSTS: "local:redis:6379"