version: '3.1'

volumes:
  vol_mariadb:

services:
  db:
    image: mariadb:10.6
    restart: always
    volumes:
     - vol_mariadb:/data/db2
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe

  app:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1